### ISSUE TITLE
wtf?

### ISSUE THREAD

**Issue by ze00** [Juanan557/android_device_xiaomi_rosy#1]

**Comment by ghost** [comment]
What Do need?

**Comment by ze00** [comment]
@ChalapathiRevanth I'm the owner of this repository. But I'm haven't to release it to Github.

https://github.com/Juanan557/android_device_xiaomi_rosy/blob/lineage-14.1/liblight/a.py
See title of this file.

**Comment by ghost** [comment]
So u Gave it to Him? @ze00

**Comment by ze00** [comment]
@ChalapathiRevanth No, I don't know him.
I provide this source to a Russia friend.
He promise to me just personal use.

**Comment by ghost** [comment]
@ze00 u uploaded this tree to yandex and have it to ur friend? If yes then this tree was Leaked By friend itself

**Comment by ze00** [comment]
@ChalapathiRevanth No, I'm sent it using QQ(a online chat software on China).
This source leaked will not take any problem to me.
But I'm feel so sad.

**Comment by ghost** [comment]
@ze00  Feeling sad bro, but @Juanan557  is not a Noob and a kanger! He might have taken some cherry-picks or like that

**Comment by ze00** [comment]
@ChalapathiRevanth That are great...and, where did you found this source?

**Comment by ghost** [comment]
@ze00 i know him, so obviously i would get

**Comment by ghost** [comment]
@ze00 I Need to Talk to Regarding this Device Tree! Is there any Telegram Account For You? Kindly Mention it Here! Or Ping Me At @ChalapathiRevanth
